# Numpy
#### Numpy is a linear algebra library for python.
Numpy is also incredibly fast, as it has bindings to C libraries.

## Install
`conda install numpy`
`pip install numpy`

## Usage
* Numpy Arrays are the main way we use Numpy
* Numpy Arrays comes in two flavors: vectors and matrices
* Vectors are strictly 1-D arrays and metrices are 2-D(can also be one row and one column)

# Numpy Arrays

In [2]:
my_list = [1, 2, 3]

In [6]:
import numpy as np

In [9]:
arr = np.array(my_list) # casting my_list to numpy array
arr

array([1, 2, 3])

In [11]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] 

In [14]:
matrix = np.array(my_matrix) # casting list of list to numpy array
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.arange(0, 10) # built in range for array creation in numpy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [21]:
np.zeros(3) # creating arrays of zeros

array([ 0.,  0.,  0.])

In [23]:
np.zeros((2, 3)) # creating multidimensional arrays by passing tuple

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [25]:
np.ones(4) #creating array of ones

array([ 1.,  1.,  1.,  1.])

In [27]:
np.ones((3, 4)) 

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [29]:
np.linspace(0, 5, 10) # evenly space between 0, 5

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [30]:
np.eye(4) # identity matrix

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [32]:
np.random.rand(5) # random arrays of size 5 between [0, 1)

array([ 0.52987884,  0.18277041,  0.44532099,  0.73992831,  0.65815769])

In [33]:
np.random.rand(3, 3) # random 2-d arrays 

array([[ 0.48624667,  0.7855636 ,  0.50925957],
       [ 0.98147115,  0.80619286,  0.76001122],
       [ 0.20159724,  0.63681917,  0.32313047]])

In [35]:
np.random.randn(5)

array([-0.66163656, -1.29527171,  2.30605323, -0.12138235,  2.25140072])

In [37]:
np.random.randn(3, 3)

array([[ 0.08263755,  0.03179721,  0.43020552],
       [ 0.94979441,  0.77350504, -0.2767784 ],
       [-0.6806237 , -1.14367735,  0.79167796]])

In [39]:
np.random.randint(1, 100) # random integer

76

In [40]:
np.random.randint(1, 100, 10) # 10 random integer between 1, 100

array([66, 80, 74, 26, 38,  2, 49, 56, 21, 15])

In [42]:
arr = np.arange(0, 25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
rand_arr = np.random.randint(0, 100, 10)
rand_arr

array([26, 30, 72, 20, 18, 82, 52, 15, 64, 30])

In [45]:
arr.reshape(5, 5) # reshaping arr to 5 rows and 5 columns

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
arr.reshape(5, 10) # dimension must satisfy the number of elements in the array here 5 * 10 != 25

ValueError: cannot reshape array of size 25 into shape (5,10)

In [47]:
arr.reshape(4, 5) # same case
arr

ValueError: cannot reshape array of size 25 into shape (4,5)

In [48]:
arr.max() # getting maximum value in arr

24

In [49]:
arr.min() # getting minimum value

0

In [50]:
arr.argmax() # getting index of maximum value

24

In [51]:
arr.argmin() # getting index of minimum value

0

In [53]:
arr = arr.reshape(5, 5)

In [55]:
np.shape(arr) # getting shape of the array

(5, 5)

In [56]:
arr.dtype # getting the datatype of the arr

dtype('int64')

# Numpy Indexing and Selection

In [57]:
arr = np.arange(0, 11)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr[3] # arr[index]

3

In [60]:
arr[1:5] # arr[start: stop]

array([1, 2, 3, 4])

In [61]:
arr[1:5:2] # arr[start:stop:step]

array([1, 3])

In [63]:
arr[1:5] = 10
arr

array([ 0, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

In [64]:
arr = np.arange(0, 11)

In [66]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [68]:
arr_2d[0][0]

5

In [69]:
arr_2d[0]

array([ 5, 10, 15])

In [70]:
# Single column index
arr_2d[2, 1] # arr[row, column]

40

In [72]:
# slicing in 2-d array
arr_2d[:2,1:] # arr[start:stop, start:stop] first slice is row and second slice is column

array([[10, 15],
       [25, 30]])

In [73]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [74]:
arr = np.arange(1, 11)

In [75]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
arr > 5 # returns array of booleans according to condtion

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [77]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [78]:
arr[bool_arr] # boolen selection return elements when boolean is True

array([ 6,  7,  8,  9, 10])

In [79]:
arr[arr < 3]

array([1, 2])

In [81]:
arr_2d = np.arange(50).reshape(5, 10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [83]:
arr_2d[2:4, :2] # grabing rows 2, 3 and column 0 and 1

array([[20, 21],
       [30, 31]])

# Numpy Operations
* Array with Array
* Array Scalars
* Universal Array functions

In [84]:
import numpy as np

In [85]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [86]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38])

In [87]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [88]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [89]:
arr + 2 # array with scalars

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21])

In [90]:
arr / arr

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,
         1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [91]:
1 / arr

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ,  0.09090909,  0.08333333,  0.07692308,  0.07142857,
        0.06666667,  0.0625    ,  0.05882353,  0.05555556,  0.05263158])

In [92]:
arr ** 2 # squaring

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361])

In [93]:
# universal array method
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739,
        3.87298335,  4.        ,  4.12310563,  4.24264069,  4.35889894])

In [94]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04,   5.98741417e+04,
         1.62754791e+05,   4.42413392e+05,   1.20260428e+06,
         3.26901737e+06,   8.88611052e+06,   2.41549528e+07,
         6.56599691e+07,   1.78482301e+08])

In [95]:
np.max(arr)

19

In [96]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])

In [97]:
np.log(arr)

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509,  2.39789527,  2.48490665,  2.56494936,  2.63905733,
        2.7080502 ,  2.77258872,  2.83321334,  2.89037176,  2.94443898])